openapi: 3.0.0
info:
  title: Svenssons Hantverk AB Staffing API
  description: API for retrieving staffing and booking data
  version: 1.0.0
servers:
  - url: https://https://yrgo-web-services.netlify.app/booking
paths:
  /bookings:
    get:
      summary: Retrieve all bookings for the given duration
      description: Returns all bookings within a given date range, or four weeks starting from this week
      parameters:
        - name: start
          in: query
          required: false
          schema:
            type: string
            format: date
        - name: end
          in: query
          required: false
          schema:
            type: string
            format: date
      responses:
        '200':
          description: A list of bookings
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  required: [name, professions, bookings]
                  properties:
                    name:
                      type: string
                      example: "Bosse Bredsladd"
                    professions:
                      type: array
                      items:
                        type: string
                        enum: [Carpenter, Electrician, Painter, Mason, Plumber]
                      example: [Carpenter, Painter]
                    bookings:
                      type: array
                      items:
                        type: object
                        required: [activity, from, to, percentage, status]
                        properties:
                          activity:
                            type: string
                            enum: [Carpenter, Electrician, Painter, Mason, Plumber, Other]
                            example: Painter
                          from:
                            type: string
                            format: date
                          to:
                            type: string
                            format: date
                          percentage:
                            type: integer
                            enum: [50, 100]
                            example: 100
                          status:
                            type: string
                            enum: [Absent, Booked, Preliminary]
                            example: Booked
